import type { Metadata } from "next";
import "./globals.css";
import { Theme as RadixTheme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <RadixTheme>{children}</RadixTheme>
      </body>
    </html>
  );
}
