export default {
  products: [
    {
      _id: "1",
      name: "tree01 3d model",
      category: "Nature",
      image: "/images/tree_modeling.jpg",
      price: 1.2,
      size: "3.1mb",
      rating: 4.5,
      numReviews: 7,
      format: "fbx",
      texture: true,
      rig: false,
      license: "public",
      description: " street tree 3d moding file",
    },
    {
      _id: "2",
      name: "human basic model",
      category: "Character",
      image: "/images/human_modeling.jpg",
      price: 0.8,
      size: "1.2mb",
      rating: 4.5,
      numReviews: 3,
      format: "obj",
      texture: false,
      rig: true,
      license: "public",
      description: "charater modeling basis 3d file",
    },
    {
      _id: "3",
      name: "sports car",
      category: "Car",
      image: "/images/sportcar_modeling.jpg",
      price: 2,
      size: "5.3mb",
      rating: 3.5,
      numReviews: 5,
      format: "fbx",
      texture: false,
      rig: false,
      license: "private",
      description: "sports car 3d model of z4 bmw",
    },
    {
      _id: "4",
      name: "study chair",
      category: "Interior",
      image: "/images/chair_modeling.jpg",
      price: 2.3,
      size: "0.8mb",
      rating: 4.3,
      numReviews: 2,
      format: "fbx",
      texture: true,
      rig: false,
      license: "public",
      description: "study room with desk",
    },
    {
      _id: "5",
      name: "gallaxy s7",
      category: "Electronics",
      image: "/images/smartphone_modeling.jpg",
      price: 2,
      size: "1.2mb",
      rating: 3.8,
      numReviews: 11,
      format: "ma",
      texture: true,
      rig: false,
      license: "commercial",
      description: "samsung electronics product",
    },
    {
      _id: "6",
      name: "ak14",
      category: "Game",
      image: "/images/ak14_modeling.jpg",
      price: 1.7,
      size: "1.4mb",
      rating: 4,
      numReviews: 3,
      format: "max",
      texture: true,
      rig: false,
      license: "public",
      description: "using fps game ",
    },
  ],
};
